### ISSUE TITLE
All F-P annotations missing from inferred GAF

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1683]
Contains  CC annotations only

**Comment by mah11** [comment]
possible false alarm - may refer to pombase-prediction.gaf rather than gene_association.pombase.inf.gaf

**Comment by ValWood** [comment]
I'm sooo confused......;)

**Comment by ValWood** [comment]
Are these file changes documented/announced anywhere? Did I miss it?

**Comment by ValWood** [comment]
Hello, can sombody help us to locate the inferred gaf?
We asked last week, and follow @dougli1sqrd  instructions, but this wasn't the file we were looking for.
Now it seems that we are all thoroughly confused ;)

More here:
https://github.com/pombase/pombase-chado/issues/639#issuecomment-342778920

**Comment by ValWood** [comment]
Start at the end of 
pombase/pombase-chado#639 (comment)

**Comment by tberardini** [comment]
We get the TAIR inf file (gene_association.tair.inf.gaf). This is the file our automatic loading scripts are built to ingest.

http://build.berkeleybop.org/view/GAF/job/gaf-check-tair/lastBuild/artifact/

I didn't know the other file (like %-prediction.gaf) existed.

http://build.berkeleybop.org/job/go-gaf-release-snapshot/lastSuccessfulBuild/artifact/pipeline/target/groups/tair/

When did these appear?

**Comment by ValWood** [comment]
We decided in the meantime to go back to the Jenkins location, not the one we were directed to recently. I reopened the tickets where I thought the redundancy issues were fixed because I was looking at a different file it seems.

Note that the issue *Still* exists  (reported independently by me and Midori), that some expected annotations are missing.

**Comment by ValWood** [comment]
See also
https://github.com/geneontology/go-annotation/issues/1336

**Comment by tberardini** [comment]
@ValWood @mah11 I checked our inferred file (the jenkins linked one, gene_association.tair.inf.gaf) and F-P inferred annotations are still present there as expected.  I see process and component annotations.  FYI.

**Comment by mah11** [comment]
Yes, the gene_association.pombase.inf.gaf at GO Jenkins has BP annotations inferred from MF-BP links (and CC annotations from whatever??). But it doesn't have _as many_ inferred BP annotations as we expect, per #1336. Are any missing from yours?

**Comment by tberardini** [comment]
Ok, clearer now.  I checked TAIR annotations for GO:0005484, which is part_of GO:0061025.  We have experimental annotations to the function term GO:0005484 which do NOT have inferred annotations to GO:0061025 in the gene_association.tair.inf.gaf file.

I checked the stanza in the GO file, the relationship is definitely there.

> [Term]
id: GO:0005484
name: SNAP receptor activity
namespace: molecular_function
alt_id: GO:0005485
alt_id: GO:0005486
def: "Acting as a marker to identify a membrane and interacting selectively with one or more SNAREs on another membran\
e to mediate membrane fusion." [GOC:mah, PMID:14570579]
subset: goslim_chembl
synonym: "Q-SNARE activity" NARROW []
synonym: "R-SNARE activity" NARROW []
synonym: "SNAP-25" NARROW []
synonym: "SNARE" EXACT []
synonym: "t-SNARE activity" NARROW []
synonym: "v-SNARE activity" NARROW []
is_a: GO:0005515 ! protein binding
**relationship: part_of GO:0061025 ! membrane fusion**

Here's one example of a gene with IDA for GO:0005484 but no IDA annotation that's inferred for membrane fusion'.  There is, however, a TAS annotation for 'membrane fusion'.  

Is there some sort of trumping going on?  If annotation exists for term X (part_of term Y), then inferred annotation for term X is not added, regardless of evidence code of annotation to term Y?

**Comment by ValWood** [comment]
Nope I don't think so, since  we have examples of missing F-P annotations with no existing annotation. Conversely we have lots of examples of redundant annotation where we get a less specific annotations than the one we made manually from  same paper from the F-P pipeline....

**Comment by tberardini** [comment]
One hypothesis squashed.

**Comment by ValWood** [comment]
Hi @dougli1sqrd  could you confirm where we are supposed to get the inferred gaf data from. Then I can figure if we are missing anything and  hopefully close. It might be a non-issue but I got confused by the thread.

Once we know we are absolutely using the correct file, we can proceed to check whether we are still missing  the reported F-P link generated annotatins.
Val

**Comment by ValWood** [comment]
see also
https://github.com/geneontology/go-annotation/issues/1674

**Comment by ValWood** [comment]
@dougli1sqrd  @cmungall  could you please help us by confirming where we are currently supposed to get these files from.  The location  might have changed, I am not sure. Once we have established which files are the current up-to-date files we can then look again to see if the issue with the missing F-P links is still current.

**Comment by dougli1sqrd** [comment]
Hi @ValWood, 
Thanks for your patience, we've been developing the new pipeline I've had to consult with Chris and Seth on where things should be. 

So our current pipeline produces a -prediction.gaf, and I can provide you with a link to the pombase-prediction.gaf:
http://snapshot.geneontology.org/annotations/pombase-prediction.gaf Is produced daily, and our current monthly release can be found at http://current.geneontology.org/annotations/pombase-prediction.gaf

We currently don't produce a *.inf.gaf, like you refer to in this ticket and in others.

**Comment by ValWood** [comment]
so to be clear this replaces   *.inf.gaf?

This is our internal thread:
https://github.com/pombase/pombase-chado/issues/639

Summary (I think)
1. There used to be a file called inf.gaf that we were told to use
2. This changed to pombase-prediction.gaf and the location changed, (not announced)
3. Now pombase-prediction.gaf has fully replaced  inf.gaf (not announced)
Is this correct?

If so, the replacement file pombase-prediction.gaf  ONLY contins component annotation s, which is the problem I reported originlly before all of the confusion about which file we should be using...

It seem possible that the F-P links have disappeared.
Which probably explains #1674

**Comment by dougli1sqrd** [comment]
Yes, I just confirmed with @cmungall that *-prediction.gaf is a different name for *.inf.gaf, but are the same contents (the name changed to -prediction). Apologies for the confusion!

As far as missing F-P missing links, I will look into what owltools is doing (that's what produces this file). I haven't ventured into owltools prediction gaf before, but I'll see what I can do!

**Comment by ValWood** [comment]
Ok thanks! it would be good to get the missing inferences back.

It would also be good to announce the file name and location change. most groups will not know, we only discovered this by chance.

Val

**Comment by dougli1sqrd** [comment]
Hi Val, I was wondering if you could give specific examples of annotations you're expecting to see given what your GAF looks like? And you're saying you used to have the F-P links in these -prediction (.inf.gaf) files?

**Comment by ValWood** [comment]
so, what I am looking for is the correct location for the file which contains the  F-P (function process) inferences.

It does not appear to be in here with the other files:

http://build.berkeleybop.org/job/go-gaf-release-snapshot/lastSuccessfulBuild/artifact/pipeline/target/groups/pombase/

**Comment by ValWood** [comment]
There are 2 files of "inferences"

pombase-prediction.gaf | 11.47 KB | view
contains ONLY cellular component data

pombase-prediction-experimental.gaf | 0 B | view
empty

**Comment by ValWood** [comment]
This is the file I am looking for.
Is this the current version?

http://build.berkeleybop.org/view/GAF/job/gaf-check-pombase/gene_association.pombase.inf.gaf

**Comment by ValWood** [comment]
If we are getting the F-P inferences file from the correct (current) location,
this ticket can be closed.

Once we know we are using the correct (i.e current) file, we can check whether the issue of missing annotations still exists, reported here.

https://github.com/geneontology/go-annotation/issues/1336

**Comment by ValWood** [comment]
I'll close this ticket, it's way too confusing.
All we want to know is are we using the correct inf.gaf (the one with processes infererred from F-P links data) ...because there appear to be numerous problems with the contents of the file we are using. This may be because we are not using the correct file.

I opened a new ticket for this. Hopefully it is clear.
inferred gaf (F-P) links, correct location and possible bugs #524
