### ISSUE TITLE
PANTHER:PTN000042666 PANTHER:PTN000042665

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#1959]
from:
https://github.com/geneontology/go-annotation/issues/1873

both referring to
https://www.pombase.org/gene/SPAC11E3.12

- [ ] SPAC11E3.12	mitochondrial thioredoxin family protein		mitochondrial electron 
transport, NADH to ubiquinone		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000042666			PAINT_REF:10371

- [ ] SPAC11E3.12	mitochondrial thioredoxin family protein		respiratory electron transport chain		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000042665			PAINT_REF:10371	20170427

- [ ] SPAC11E3.12	mitochondrial thioredoxin family protein		NADH dehydrogenase (ubiquinone) activity		GO_Central	Schizosaccharomyces pombe	IBA	PANTHER:PTN000042665			PAINT_REF:10371	20170427

(we discussed in detail this week about the other protein which is a member of the NADH complex in fungi)

**Comment by ValWood** [comment]
See
https://github.com/geneontology/go-annotation/issues/31
for some history

**Comment by thomaspd** [comment]
@marcfeuermann can you please look into the annotations for PTHR10371.  Specifically, it sounds like Val is suggesting that there should be a loss of these functions for the pombe ortholog, as it lacks a mitochondrial electron transport I system (@ValWood is that correct?)

**Comment by ValWood** [comment]
Yes. Essentially complexI in metazoa is a large >44 subunit complex. It is clearly multifunctional, but it is not well studied. It does have NADH dehydrogenase activity. In yeast  (at least pombe and cerevisiae, but not all yeast) this function is performed by a completely different protein. 

however pombe has  3/>44 subunits (I think cerevisiae has 1, or 2). There is speculation that these have a role in iron sulphur cluster protein assembly or lipid metabolism, but essentially we don't know what they do. All we know is they aren't  part of the electron transport chain.

**Comment by marcfeuermann** [comment]
It seems that this has already been corrected by Pascale on 2018-09-04.

**Comment by thomaspd** [comment]
Thanks, I will close this issue.

**Comment by ValWood** [comment]
I still see the annotations her, should I? Oct seems a long time ago?

**Comment by marcfeuermann** [comment]
I'm sorry, I can check PTHR10371 again and again, but the fact is that all propagations have been blocked  for PTN000822143 by Pascale on 2018-09-04. The problem is not on the PAINT annotation side.  May be @huaiyumi you might find why they did not disappear ?
Thanks
Marc.

**Comment by ValWood** [comment]
Thansk Marc, Assigned to @huaiyumi

**Comment by pgaudet** [comment]
SPAC11E3.12 has no more IBas
