### ISSUE TITLE
Apn2/APEX2 isn' phosphodiesterase I activity

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#3812]
* **PTHR ID & PTN node:**

UniProtKB:Q9UBZ4 | APEX2 | enables | GO:0004528&nbsp;&nbsp;&nbsp;&nbsp;phosphodiesterase I activity | ECO:0000318&nbsp;&nbsp;&nbsp;IBA | PMID:21873635 | PANTHER:PTN000507731 more... | 9606 Homo sapiens | GO_Central

seems to be a 3' phosphodiesterase  and  phosphodiesterase I  is 5'

* **Sequences with problematic annotation (ID + gene/protein name):**
e.g.
https://www.uniprot.org/uniprot/Q9UBZ4

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

annotation error, PomBase and TAIR

**Comment by ValWood** [comment]
background:
https://github.com/geneontology/go-ontology/issues/21569

**Comment by tberardini** [comment]
@ebakker2 Can you please look into this?  Thanks.

**Comment by marcfeuermann** [comment]
This has been fixed at the PAINT level.

**Comment by ValWood** [comment]
Apologies Mark, it is possible this was correct. It still isn't clear to me.....
https://github.com/geneontology/go-ontology/issues/21569

**Comment by marcfeuermann** [comment]
In fact I've kept the parent phosphoric diester hydrolase activity for which we have many evidences. I would propose to keep it like that as long as there is a doubt.
