### ISSUE TITLE
 PTN000354756 not all ESCRT-0 complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#4012]
* **PTHR ID & PTN node:**

GO:0033565 | ESCRT-0 complex | IBA with WBGene00004109 , Q92783 , hse1 , PTN000354756 , S000000994

* **Sequences with problematic annotation (ID + gene/protein name):**

https://www.pombase.org/gene/SPCC1919.11

* **Type of Issue: Erroneous source or erroneous propagation, or other issue**

erroneous propagation
SPCC1919.11 is not the ortholog of SGD:S000000994 HSE1- 
that's https://www.pombase.org/gene/SPBC1734.08

SPCC1919.11 doesn't have an s.cerevisiae ortholog, but the human ortholog is 
SH3GL3 which isn't escrt-0

**Comment by marcfeuermann** [comment]
Done

**Comment by ValWood** [comment]
I still see this annoation  for lsb1 in AmiGO:
<img width="850" alt="error PAINT 4" src="https://github.com/geneontology/go-annotation/assets/7359272/52d6ffe7-7147-4a26-bdd4-5adae2a8b407">

both of these annotations seem to be incorrect for Lsb1
(one. of the supporting annotations is another pom be protein https://www.pombase.org/gene/SPBC1734.08 hse1)

SGD lsb1 also gets these erroneous propagations
https://www.yeastgenome.org/locus/S000003368/go#comp

**Comment by marcfeuermann** [comment]
In fact BPs were blocked for the the whole fungal node including S. pombe mug137 and lsb1 (PTN007651104), but CCs were only blocked for single mug137. Could be a problem of transfer of NOT annotations during PANTHER version change. I've now blocked all for PTN007651104.
