### ISSUE TITLE
Problem with RHea mapping 	IEA with 13065

### ISSUE THREAD

**Issue by ValWood** [geneontology/go-annotation#5491]
I am getting 79 annotations to 
chromatin extrusion motor activity
--
  | bip1, brr2, cdc28, cdc48, chl1, cta5, dbp10, dbp2, dbp3, dbp5, dbp6, dbp7, dbp8, dbp9, ddx27, dhx37, dna2, fal1, fap7, fbh1, fft1, fft2, fft3, fml1, fml2, gih35, has1, hca4, hrq1, hrr1, ino80, lsh1, mak5, mcm2, mcm3, mcm4, mcm5, mcm6, mcm7, mrh5, mss116, pfh1, pku70, pku80, prh1, prp11, prp16, prp22, prp28, prp43, ptr8, rad15, rad50, rad54, rdh54, rok1, rpm2, rqh1, rqt2, rrp3, rvb1, rvb2, sks2, spb4, srs2, ste13, sum3, swr1, tif1, tlh1, tlh2, uap56, ucp12, upf1, vps4, yta12, SPBC56F2.07c, SPCC1672.11c, SPCC737.07c

**Comment by ValWood** [comment]
and 81 to cohesin loader 

cohesin loader activity
--
  | bip1, brr2, cdc28, cdc48, chl1, cta5, dbp10, dbp2, dbp3, dbp5, dbp6, dbp7, dbp8, dbp9, ddx27, dhx37, dna2, fal1, fap7, fbh1, fft1, fft2, fft3, fml1, fml2, gih35, has1, hca4, hrq1, hrr1, ino80, lsh1, mak5, mcm2, mcm3, mcm4, mcm5, mcm6, mcm7, mis4, mrh5, mss116, pfh1, pku70, pku80, prh1, prp11, prp16, prp22, prp28, prp43, ptr8, rad15, rad50, rad54, rdh54, rok1, rpm2, rqh1, rqt2, rrp3, rvb1, rvb2, sks2, spb4, srs2, ssl3, ste13, sum3, swr1, tif1, tlh1, tlh2, uap56, ucp12, upf1, vps4, yta12, SPBC56F2.07c, SPCC1672.11c, SPCC737.07c

**Comment by ValWood** [comment]
and 89 to DNA clamp loader


DNA clamp loader activity
bip1, brr2, cdc28, cdc48, chl1, cta5, ctf18, ctf8, dbp10, dbp2, dbp3, dbp5, dbp6, dbp7, dbp8, dbp9, dcc1, ddx27, dhx37, dna2, fal1, fap7, fbh1, fft1, fft2, fft3, fml1, fml2, gih35, has1, hca4, hrq1, hrr1, ino80, lsh1, mak5, mcm2, mcm3, mcm4, mcm5, mcm6, mcm7, mrh5, mss116, pfh1, pku70, pku80, prh1, prp11, prp16, prp22, prp28, prp43, ptr8, rad15, rad17, rad50, rad54, rdh54, rfc1, rfc2, rfc3, rfc4, rfc5, rok1, rpm2, rqh1, rqt2, rrp3, rvb1, rvb2, sks2, spb4, srs2, ste13, sum3, swr1, tif1, tlh1, tlh2, uap56, ucp12, upf1, vps4, yta12, SPBC56F2.07c, SPCC1672.11c, SPCC737.07c

**Comment by ValWood** [comment]
many off-target annotations to histone chaperone


ATP-dependent H2AZ histone chaperone activity
--
  | bip1, brr2, cdc28, cdc48, chl1, cta5, dbp10, dbp2, dbp3, dbp5, dbp6, dbp7, dbp8, dbp9, ddx27, dhx37, dna2, fal1, fap7, fbh1, fft1, fft2, fft3, fml1, fml2, gih35, has1, hca4, hrq1, hrr1, ino80, lsh1, mak5, mcm2, mcm3, mcm4, mcm5, mcm6, mcm7, mrh5, mss116, pfh1, pku70, pku80, prh1, prp11, prp16, prp22, prp28, prp43, ptr8, rad15, rad50, rad54, rdh54, rok1, rpm2, rqh1, rqt2, rrp3, rvb1, rvb2, sks2, spb4, srs2, ste13, sum3, tif1, tlh1, tlh2, uap56, ucp12, upf1, vps4, yta12, SPBC56F2.07c, SPCC1672.11c, SPCC737.07c

[ATP-dependent H2AZ histone chaperone activity](https://www.pombase.org/term/GO:0140849)
[bip1](https://www.pombase.org/gene/SPAC22A12.15c), [brr2](https://www.pombase.org/gene/SPAC9.03c), [cdc28](https://www.pombase.org/gene/SPBC19C2.01), [cdc48](https://www.pombase.org/gene/SPAC1565.08), [chl1](https://www.pombase.org/gene/SPAC3G6.11), [cta5](https://www.pombase.org/gene/SPAC29A4.19c), [dbp10](https://www.pombase.org/gene/SPAC31A2.07c), [dbp2](https://www.pombase.org/gene/SPBP8B7.16c), [dbp3](https://www.pombase.org/gene/SPBC17D1.06), [dbp5](https://www.pombase.org/gene/SPBC12C2.06), [dbp6](https://www.pombase.org/gene/SPCC285.03), [dbp7](https://www.pombase.org/gene/SPBC21H7.04), [dbp8](https://www.pombase.org/gene/SPBC543.06c), [dbp9](https://www.pombase.org/gene/SPCC1494.06c), [ddx27](https://www.pombase.org/gene/SPAC30D11.03), [dhx37](https://www.pombase.org/gene/SPAPB1A10.06c), [dna2](https://www.pombase.org/gene/SPBC16D10.04c), [fal1](https://www.pombase.org/gene/SPAC1F5.10), [fap7](https://www.pombase.org/gene/SPCC830.11c), [fbh1](https://www.pombase.org/gene/SPBC336.01), [fft1](https://www.pombase.org/gene/SPAC20G8.08c), [fft2](https://www.pombase.org/gene/SPCC1235.05c), [fft3](https://www.pombase.org/gene/SPAC25A8.01c), [fml1](https://www.pombase.org/gene/SPAC9.05), [fml2](https://www.pombase.org/gene/SPAC20H4.04), [gih35](https://www.pombase.org/gene/SPAC20H4.09), [has1](https://www.pombase.org/gene/SPAC1F7.02c), [hca4](https://www.pombase.org/gene/SPAC1093.05), [hrq1](https://www.pombase.org/gene/SPAC23A1.19c), [hrr1](https://www.pombase.org/gene/SPCC1739.03), [ino80](https://www.pombase.org/gene/SPAC29B12.01), [lsh1](https://www.pombase.org/gene/SPAC1F5.06), [mak5](https://www.pombase.org/gene/SPBC4F6.07c), [mcm2](https://www.pombase.org/gene/SPBC4.04c), [mcm3](https://www.pombase.org/gene/SPCC1682.02c), [mcm4](https://www.pombase.org/gene/SPCC16A11.17), [mcm5](https://www.pombase.org/gene/SPAC1B2.05), [mcm6](https://www.pombase.org/gene/SPBC211.04c), [mcm7](https://www.pombase.org/gene/SPBC25D12.03c), [mrh5](https://www.pombase.org/gene/SPBC25D12.06), [mss116](https://www.pombase.org/gene/SPBC691.04), [pfh1](https://www.pombase.org/gene/SPBC887.14c), [pku70](https://www.pombase.org/gene/SPCC126.02c), [pku80](https://www.pombase.org/gene/SPBC543.03c), [prh1](https://www.pombase.org/gene/SPAC2G11.11c), [prp11](https://www.pombase.org/gene/SPCC10H11.01), [prp16](https://www.pombase.org/gene/SPBC1711.17), [prp22](https://www.pombase.org/gene/SPAC10F6.02c), [prp28](https://www.pombase.org/gene/SPCC63.11), [prp43](https://www.pombase.org/gene/SPBC16H5.10c), [ptr8](https://www.pombase.org/gene/SPAC17A5.06), [rad15](https://www.pombase.org/gene/SPAC1D4.12), [rad50](https://www.pombase.org/gene/SPAC1556.01c), [rad54](https://www.pombase.org/gene/SPAC15A10.03c), [rdh54](https://www.pombase.org/gene/SPAC22F3.03c), [rok1](https://www.pombase.org/gene/SPAC22F3.08c), [rpm2](https://www.pombase.org/gene/SPAC637.11), [rqh1](https://www.pombase.org/gene/SPAC2G11.12), [rqt2](https://www.pombase.org/gene/SPBC13G1.10c), [rrp3](https://www.pombase.org/gene/SPAC823.08c), [rvb1](https://www.pombase.org/gene/SPAPB8E5.09), [rvb2](https://www.pombase.org/gene/SPBC83.08), [sks2](https://www.pombase.org/gene/SPBC1709.05), [spb4](https://www.pombase.org/gene/SPBC24C6.02), [srs2](https://www.pombase.org/gene/SPAC4H3.05), [ste13](https://www.pombase.org/gene/SPBC776.09), [sum3](https://www.pombase.org/gene/SPCC1795.11), [tif1](https://www.pombase.org/gene/SPAC1006.07), [tlh1](https://www.pombase.org/gene/SPAC212.11), [tlh2](https://www.pombase.org/gene/SPBCPT2R1.08c), [uap56](https://www.pombase.org/gene/SPAC17G6.14c), [ucp12](https://www.pombase.org/gene/SPCC895.09c), [upf1](https://www.pombase.org/gene/SPAC16C9.06c), [vps4](https://www.pombase.org/gene/SPAC2G11.06), [yta12](https://www.pombase.org/gene/SPBC543.09), [SPBC56F2.07c](https://www.pombase.org/gene/SPBC56F2.07c), [SPCC1672.11c](https://www.pombase.org/gene/SPCC1672.11c), [SPCC737.07c](https://www.pombase.org/gene/SPCC737.07c)

**Comment by ValWood** [comment]
etc...

**Comment by pgaudet** [comment]
Fixed - in the previous release (2024-09-08), the RHEA2GO file had the following mappings: 

>RHEA:13065 > GO:DNA clamp loader activity ; GO:0003689
RHEA:13065 > GO:ATP hydrolysis activity ; GO:0016887
RHEA:13065 > GO:cohesin loader activity ; GO:0061775
RHEA:13065 > GO:chromatin extrusion motor activity ; GO:0140584
RHEA:13065 > GO:ATP-dependent H3-H4 histone complex chaperone activity ; GO:0140665
RHEA:13065 > GO:ATP-dependent H2AZ histone chaperone activity ; GO:0140849

In the lastest release (2024-11-04). there is this single mapping. 

>RHEA:13065 > GO:ATP hydrolysis activity ; GO:0016887

**Comment by ValWood** [comment]
This didn't fix everything. I still have 81 annotations to cohesin loader activity

https://www.pombase.org/term/GO:0061775

**Comment by ValWood** [comment]
I'm filtering this for tomorrow so you won't see them via the link

**Comment by pgaudet** [comment]
This seems to be a bug, since it has a 'broad synonym' as all others. I'll check with Alex.

**Comment by pgaudet** [comment]
@ValWood Should I close this ? can you give us the annotations that you're filtering ?

**Comment by ValWood** [comment]
No  don't close, it definitely isn't fixed.
See https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0061775&taxonId=284812&taxonUsage=descendants

(but similar numbers for all species)

**Comment by ValWood** [comment]
Human has 220 cohesin loader annotations from this mapping
https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0061775&taxonId=9606&taxonUsage=descendants

**Comment by ValWood** [comment]
chromatin extrusion motor activity is still a problem

https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0140584&taxonId=284812&taxonUsage=descendants

and human (216)
https://www.ebi.ac.uk/QuickGO/annotations?goUsage=descendants&goUsageRelationships=is_a,part_of,occurs_in&goId=GO:0140584&taxonId=9606&taxonUsage=descendants

**Comment by ValWood** [comment]
So for example there is only a single cohesin loader consisting of ADHERIN/NIPBL &SCC4 (human names)

**Comment by pgaudet** [comment]
Hi Val, 

The RHEAs should be fixed in the upcoming GOA release (coming out in the next days), but EC might still have problems, since the data comes from Uniprot, that may be ignoring the cross-reference types. 
Alex will change [EC2GO mapping from the GO pipeline](http://snapshot.geneontology.org/ontology/external2go/ec2go) in the GOA release after the one currently in progress.

**Comment by ValWood** [comment]
OK, I think it is good to keep this ticket open to double check everything is fixed.

**Comment by pgaudet** [comment]
This seems fixed in the UniProt form last week -see bip1 

https://www.ebi.ac.uk/QuickGO/annotations?geneProductId=Q6Z7B0&aspect=molecular_function
